### PR TITLE
Update doc for thread optimization API

### PR DESCRIPTION
**Pull request by cshruti87**

### CODE REVIEW

**Comment by cshruti87** [comment]
@courtneyambrozic 
Hi Courtney, could you please review these changes for me?
I have added a demo notebook and updated the doc strings for thread optimization tool. I have also made small changes in the test file to reduce number of iterations.

**Review by courtneyambrozic — CHANGES_REQUESTED** [review]
Hey Shruti, this looks great! Thanks a lot for uploading that demo notebook. I think it's extremely helpful to see those functions in action. Now that CVPy is branching out, we might want to create separate folders under the "examples" directory . Do you think you could create a "thread_optimization" and a "biomedimage" folder to organize these examples? It looks like DLPy follows a similar organization structure: https://github.com/sassoftware/python-dlpy/tree/master/examples

**Comment by cshruti87** [comment]
@courtneyambrozic 
Thanks for the review. I will rearrange the example directory.

**Comment by cshruti87** [comment]
@courtneyambrozic 
I have rearranged the examples directory. If it looks good to you, I will go ahead and merge to main.

**Review by courtneyambrozic — APPROVED** [review]
Looks great, Shruti! Thanks!

**Pull request merged**
